name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    using: 'node18'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    using: 'node18'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Test
        run: npm run test